export const siteConfig = {
  title: 'Chronos — Inside the Watch',
  tagline: 'A luxury mechanical watch, opened layer by layer',
  mark: 'CHR',
  wordmark: 'Chronos',
  badge: '39 mm',
  hint: 'Scroll to disassemble',
  colors: {
    background: '#080808',
    foreground: '#E8E1D4',
    primary: '#C6A15B',
    secondary: '#B08948',
    accent: '#C6A15B',
    muted: '#2A2A2A',
  },
  hero: {
    eyebrow: 'A study in time',
    headline: 'Chronos',
    subtitle: 'Inside the Watch',
    lede:
      'A 39-millimeter dress watch, opened in the air. Scroll and the sapphire lifts, the hands leave the dial, and a hand-finished movement hangs above the case — gears, springs, and gold, still keeping time.',
  },
  chapters: [
    {
      id: 'assembled',
      at: 0,
      index: '01',
      title: 'Assembled',
      kicker: 'The closed instrument',
      copy: 'Closed, it is a 39-millimeter dress watch. Gold case, dark dial, sapphire over the hands.',
      body: 'From the outside it reads as one object: a round gold case, a sunburst dial, three hands parked at ten-ten, and a short leather strap. Nothing ticks on screen. Scroll, and the stack starts to come apart — crystal first, then the hands, then the movement that actually keeps the time.',
      facts: ['39 mm gold case', 'Domed sapphire crystal', 'Calibre 391 automatic'],
    },
    {
      id: 'crystal',
      at: 0.22,
      index: '02',
      title: 'Crystal',
      kicker: 'The first thing that lifts',
      copy: 'A domed sapphire and a knurled gold bezel. They lift together and the dial is suddenly in the air.',
      body: 'The crystal is a shallow dome, anti-reflective in life, clear here so the dial can be read from above. Around it, a knurled bezel catches the key light on every flute. This is the lid of the watch. Once it rises, the hands have nowhere to hide, and the chapter ring is no longer a picture behind glass.',
      facts: ['Domed sapphire', 'Knurled gold bezel', 'Rehaut under the glass'],
    },
    {
      id: 'hands',
      at: 0.4,
      index: '03',
      title: 'Hands',
      kicker: 'Hour, minute, second',
      copy: 'Three gold hands leave the dial at ten-ten, still aimed at the same hour marks they were reading.',
      body: 'Dauphine hour and minute hands, faceted so they flash when the key light hits an edge. A slender seconds hand with a counterweight sits a fraction above them on the cannon pinion. They do not spin. They peel off the dial as a set, the way a watchmaker lifts them with a hand-removing tool — except here the only tool is the scroll.',
      facts: ['Dauphine hour & minute', 'Seconds with counterweight', 'Parked at 10:10'],
    },
    {
      id: 'dial',
      at: 0.62,
      index: '04',
      title: 'Dial',
      kicker: 'The face you actually read',
      copy: 'Applied gold indexes, a railroad minute track, and a date window at three. Chronos, printed in the sunburst.',
      body: 'Twelve applied batons sit on a dark sunburst. The minute track is a ring of sixty marks; the hours that matter are metal, not ink. Below twelve, the name. Above six, Swiss Made and twenty-one jewels. At three, a date aperture framed in gold shows the seventh. This is the only layer meant to be seen when the watch is closed.',
      facts: ['12 applied gold indexes', '60-mark minute track', 'Date at 3 o’clock'],
    },
    {
      id: 'movement',
      at: 0.8,
      index: '05',
      title: 'Movement',
      kicker: 'Gears, springs, jewels',
      copy: 'A going train, a balance, a hairspring, and bridges striped with côtes de Genève. This layer is the watch.',
      body: 'The barrel feeds a train of toothed wheels into the escape wheel. A balance and hairspring at the twelve side beat the time; pallet and jewels keep the impulses honest. Gold-toned bridges carry Geneva stripes; the main plate is perlage. Screws, chatons, and a ratchet wheel are the small parts that stop this from reading as a toy. Twenty-one jewels. Calibre 391.',
      facts: ['21 ruby jewels', 'Côtes de Genève bridges', 'Balance & hairspring'],
    },
    {
      id: 'exploded',
      at: 0.94,
      index: '06',
      title: 'Exploded',
      kicker: 'Every layer named',
      copy: 'Crystal, hands, dial, movement, case, and caseback hang in space, still aligned to the same axis.',
      body: 'The watch is a drawing now: sapphire up, gears in the middle, gold case dropped away, exhibition caseback below with the serial still readable. Nothing was unscrewed. Scroll back and the sandwich reseats itself — the same 39 millimeters, closed again, hands at ten-ten.',
      facts: ['6 named layers', 'No fasteners removed', 'Scroll back to reassemble'],
    },
  ],
  callouts: [
    { layer: 'crystal', from: 0.24, to: 0.44, name: 'Sapphire', note: 'Domed crystal · knurled gold bezel', anchor: 'crystal' },
    { layer: 'hands', from: 0.42, to: 0.58, name: 'Hands', note: 'Dauphine set · parked at 10:10', anchor: 'hands' },
    { layer: 'dial', from: 0.5, to: 0.66, name: 'Dial', note: 'Sunburst · applied indexes · date', anchor: 'dial' },
    { layer: 'movement', from: 0.64, to: 0.82, name: 'Calibre 391', note: 'Going train · balance · 21 jewels', anchor: 'movement' },
    { layer: 'case', from: 0.78, to: 0.96, name: 'Case', note: '39 mm gold · lugs, crown, caseback', anchor: 'case' },
  ],
  colophon: {
    title: 'Chronos — Inside the Watch',
    fine: 'Crystal · Hands · Dial · Movement · Case · Caseback',
    note: 'A teardown you can scroll. Scroll back and every gear reseats itself in the case.',
  },
}
