export const siteConfig = {
  title: 'Nox — Open Calibre',
  tagline: 'A steel skeleton watch, opened layer by layer',
  mark: 'NOX',
  wordmark: 'Nox',
  badge: '44 mm',
  hint: 'Scroll to disassemble',
  colors: {
    background: '#0A0A0A',
    foreground: '#D5D8DC',
    primary: '#C6A15B',
    secondary: '#B08948',
    accent: '#C6A15B',
    muted: '#1A1A1A',
  },
  hero: {
    eyebrow: 'Open calibre',
    headline: 'Nox',
    subtitle: 'Open Calibre',
    lede:
      'A 44-millimeter steel skeleton on a dark stage. The dial is already gone. Scroll, and the screws lift, the sapphire leaves the case, and a gold train hangs in black bridges — still aligned to the same axis.',
  },
  chapters: [
    {
      id: 'assembled',
      at: 0,
      index: '01',
      title: 'Assembled',
      kicker: 'The closed instrument',
      copy: 'Closed, it is a 44-millimeter steel skeleton. Brushed bezel, six screws, rubber on integrated lugs.',
      body: 'From the outside it reads as one object: a thick steel case, a flat sapphire over an open movement, three hands parked at ten-ten, and a ribbed black strap. Nothing ticks on screen. Scroll, and the stack starts to come apart — screws first, then crystal, then the calibre that actually keeps the time.',
      facts: ['44 mm steel case', 'Flat sapphire crystal', 'Calibre 441 automatic'],
    },
    {
      id: 'bezel',
      at: 0.22,
      index: '02',
      title: 'Bezel',
      kicker: 'Six screws, then the glass',
      copy: 'Six H-screws lift out of the brushed steel ring. The bezel and flat sapphire rise with them.',
      body: 'The bezel is a satined steel hoop with a polished knife-edge. Six decorative screws pin it to the case — theatre, not torque. Under it, a flat sapphire, anti-reflective in life, clear here so the open calibre can be read from above. This is the lid. Once it rises, the hands have nowhere to hide.',
      facts: ['6 bezel screws', 'Brushed steel ring', 'Flat sapphire'],
    },
    {
      id: 'hands',
      at: 0.4,
      index: '03',
      title: 'Hands',
      kicker: 'Hour, minute, second',
      copy: 'Sword hour and minute hands leave the open ring at ten-ten, lume still aimed at the same bar indices.',
      body: 'Broad steel swords, skeletonized down the center and filled with lume. A slender seconds needle sits a fraction above them on the cannon pinion. They do not spin. They peel off the movement as a set — the way a watchmaker lifts them with a hand-removing tool — except here the only tool is the scroll.',
      facts: ['Skeleton sword hands', 'Lume fill', 'Seconds needle'],
    },
    {
      id: 'ring',
      at: 0.62,
      index: '04',
      title: 'Ring',
      kicker: 'No solid dial',
      copy: 'A black chapter ring and twelve silver bar indices. The center is empty on purpose.',
      body: 'There is no sunburst, no date, no printed name. Twelve applied bars sit on a matte-black rehaut; the minute track is the inner edge of that ring. Through the hole, the gold train and black bridges are the face you actually read. This layer is a frame, not a cover.',
      facts: ['Applied lume indices', 'Railroad minute track', 'Black rehaut'],
    },
    {
      id: 'movement',
      at: 0.8,
      index: '05',
      title: 'Calibre',
      kicker: 'Gears, bridges, jewels',
      copy: 'Matte-black bridges lift off a gold going train. A ruby catches the key light at nine.',
      body: 'The barrel feeds a train of toothed wheels into the escape. A balance and hairspring beat the time; pallet and jewels keep the impulses honest. Black plates are cut away so the brass shows. Screws and chatons stop this from reading as a toy. Twenty-five jewels. Calibre 441.',
      facts: ['Gold going train', 'Matte black bridges', 'Ruby jewel'],
    },
    {
      id: 'exploded',
      at: 0.94,
      index: '06',
      title: 'Exploded',
      kicker: 'Every layer named',
      copy: 'Screws, crystal, hands, ring, movement, case, and strap hang in space, still aligned to the same axis.',
      body: 'The watch is a drawing now: sapphire up, gold train in the middle, steel case and rubber dropped away, exhibition caseback below. Nothing was unscrewed for real. Scroll back and the sandwich reseats itself — the same 44 millimeters, closed again, hands at ten-ten.',
      facts: ['6 named layers', 'Integrated lugs', 'Scroll back to reassemble'],
    },
  ],
  callouts: [
    { layer: 'crystal', from: 0.18, to: 0.38, name: 'Bezel', note: 'Six screws · brushed steel · flat sapphire', anchor: 'crystal' },
    { layer: 'hands', from: 0.4, to: 0.56, name: 'Hands', note: 'Steel swords · lume · parked at 10:10', anchor: 'hands' },
    { layer: 'dial', from: 0.5, to: 0.66, name: 'Ring', note: 'Black rehaut · railroad track · applied indices', anchor: 'dial' },
    { layer: 'movement', from: 0.64, to: 0.82, name: 'Calibre 441', note: 'Gold train · black bridges · ruby', anchor: 'movement' },
    { layer: 'case', from: 0.78, to: 0.96, name: 'Case', note: '44 mm steel · crown, lugs, rubber', anchor: 'case' },
  ],
  colophon: {
    title: 'Nox — Open Calibre',
    fine: 'Screws · Crystal · Hands · Ring · Movement · Case',
    note: 'A teardown you can scroll. Scroll back and every gear reseats itself in the case.',
  },
}
